"use client";

import { useRef, useState } from "react";
import { RESOURCE_CATEGORIES, RESOURCE_KINDS, RESOURCE_KIND_LABELS } from "@/lib/resource-types";
import type { SmartImportBatchContext, SmartImportGroup, SmartImportMergeFields, SmartImportMutationResult, SmartImportRequest, SmartImportResolutionMode, SmartImportResolutionPreview } from "@/lib/smart-import-types";
import { ManagerDialog } from "./manager-primitives";
import { SmartFeedback } from "./smart-import-feedback";
import { smartError, smartErrorStatus, smartRequest } from "./smart-api";
import styles from "./smart-import.module.css";

export function SmartImportResolve({ context, group, resourceId, onClose, onChanged }: { context: SmartImportBatchContext; group: SmartImportGroup; resourceId: string; onClose: () => void; onChanged: (value: SmartImportBatchContext) => void }) {
  const [snapshot] = useState(context); const [mode, setMode] = useState<SmartImportResolutionMode>("link");
  const [fields, setFields] = useState<Partial<SmartImportMergeFields>>({}); const [preview, setPreview] = useState<SmartImportResolutionPreview | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [status, setStatus] = useState(0); const [submitted, setSubmitted] = useState(false);
  const attempt = useRef<Extract<SmartImportRequest, { action: "resolve" }> | null>(null);
  const match = [...group.matches, ...group.suspectedMatches].find(item => item.id === resourceId);
  async function loadPreview() { if (busy) return; setBusy(true); setError(""); try { setPreview(await smartRequest<SmartImportResolutionPreview>("imports", { action: "resolve-preview", batchId: snapshot.batch.id, batchRevision: snapshot.batchRevision, groupId: group.id, resourceId, mode, ...(mode === "merge" ? { fields } : {}) })); } catch (failure) { setError(smartError(failure)); setStatus(smartErrorStatus(failure)); } finally { setBusy(false); } }
  async function confirm() {
    if (!preview || busy) return; setBusy(true); setError("");
    const payload = attempt.current ?? { action: "resolve" as const, batchId: snapshot.batch.id, batchRevision: preview.batchRevision, libraryRevision: preview.libraryRevision, confirmation: preview.confirmation, requestId: crypto.randomUUID(), groupId: group.id, resourceId, mode, ...(mode === "merge" ? { fields } : {}) }; attempt.current = payload; setSubmitted(true);
    try { const result = await smartRequest<SmartImportMutationResult>("imports", payload); onChanged(result); onClose(); } catch (failure) { setError(smartError(failure)); setStatus(smartErrorStatus(failure)); } finally { setBusy(false); }
  }
  const rows = preview ? (["name", "kind", "category", "description", "tags", "notes", "status", "visibility"] as const).map(key => ({ key, label: ({ name: "名称", kind: "类型", category: "用途", description: "说明", tags: "标签", notes: "私人备注", status: "整理状态", visibility: "展示范围" })[key], before: preview.before[key], after: preview.after[key] })) : [];
  function display(value: unknown) { if (Array.isArray(value)) return value.join("、") || "—"; return ({ tool: "工具", website: "网站", article: "文章", asset: "素材", private: "仅自己", public: "公开候选", inbox: "待整理", organized: "已整理", archived: "已归档" } as Record<string, string>)[String(value)] ?? (String(value || "—")); }
  return <ManagerDialog title="比较与处理重复资源" description="关联、恢复与合并都会先核对当前资源。公开版本需要单独发布才会变化。" onClose={onClose} busy={busy} wide><div className={styles.dialogBody}>
    <div className={styles.compareIntro}><div><span>本批候选</span><strong>{group.fields.name}</strong><p className={styles.fullUrl}>{group.representative.url}</p></div><div><span>现有收藏</span><strong>{match?.name}</strong><p className={styles.fullUrl}>{match?.url}</p></div></div>
    {!preview ? <fieldset className={styles.formFields} disabled={busy}><label>处理方式<select value={mode} onChange={event => { setMode(event.target.value as SmartImportResolutionMode); setFields({}); }}><option value="link">关联现有资源，跳过新增</option>{match?.status === "archived" ? <option value="restore">恢复归档资源为私有已整理</option> : null}<option value="merge">逐字段合并到现有资源</option></select></label>
      {mode === "merge" ? <><p className={styles.help}>只覆盖下方明确勾选的字段，未勾选的现有内容保留。名称相近或同域名也不会自动合并。</p>{(["name", "kind", "category", "description", "tags", "notes"] as const).map(key => <div className={styles.mergeField} key={key}><label className={styles.checkLabel}><input type="checkbox" checked={key in fields} onChange={event => setFields(previous => { const next = { ...previous }; if (event.target.checked) Object.assign(next, { [key]: key === "notes" ? "" : group.fields[key] }); else delete next[key]; return next; })} />{({ name: "名称", kind: "类型", category: "用途", description: "一句用途", tags: "标签", notes: "私人备注" })[key]}</label>{key in fields ? key === "kind" ? <select aria-label="合并资源类型" value={fields.kind} onChange={event => setFields(value => ({ ...value, kind: event.target.value as SmartImportMergeFields["kind"] }))}>{RESOURCE_KINDS.map(kind => <option key={kind} value={kind}>{RESOURCE_KIND_LABELS[kind]}</option>)}</select> : key === "category" ? <select aria-label="合并用途分类" value={fields.category} onChange={event => setFields(value => ({ ...value, category: event.target.value as SmartImportMergeFields["category"] }))}>{RESOURCE_CATEGORIES.map(category => <option key={category}>{category}</option>)}</select> : <textarea aria-label={`合并${key === "notes" ? "私人备注" : key === "tags" ? "标签" : key === "name" ? "名称" : "用途"}`} rows={2} value={key === "tags" ? undefined : fields[key] ?? ""} defaultValue={key === "tags" ? fields.tags?.join("，") : undefined} onChange={event => setFields(value => ({ ...value, [key]: key === "tags" ? event.target.value.split(/[,，]/).map(tag => tag.trim()).filter(Boolean) : event.target.value }))} /> : null}</div>)}</> : <p className={styles.help}>{mode === "restore" ? "恢复后为仅自己可见的已整理资源，不会自动精选或公开。" : "保留现有资源与全部字段，仅记录本批候选已关联。"}</p>}
    </fieldset> : <><div className={styles.comparisonTable}><div className={styles.comparisonHeader}><strong>字段</strong><strong>当前内容</strong><strong>确认后</strong></div>{rows.map(row => <div key={row.key} className={JSON.stringify(row.before) !== JSON.stringify(row.after) ? styles.changedField : undefined}><strong>{row.label}</strong><span>{display(row.before)}</span><span>{display(row.after)}</span></div>)}</div><p className={styles.help}>高亮字段会改变。私人备注、精选、常用等未选择字段由预览结果确认。</p></>}
    <SmartFeedback error={error} status={status} /><div className={styles.dialogActions}><button type="button" className={styles.secondaryButton} disabled={busy} onClick={preview && !submitted ? () => setPreview(null) : onClose}>{preview && !submitted ? "返回调整" : "返回候选"}</button><button type="button" className={styles.primaryButton} disabled={busy || status === 409 || (mode === "merge" && !Object.keys(fields).length)} onClick={preview ? confirm : loadPreview}>{busy ? "正在核对…" : preview ? "确认这次处理" : "预览字段变化"}</button></div>
  </div></ManagerDialog>;
}
