"use client";

import Link from "next/link";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { RESOURCE_CATEGORIES, RESOURCE_KINDS, RESOURCE_KIND_LABELS } from "@/lib/resource-types";
import type { SmartImportBatchContext, SmartImportDecision, SmartImportFilters, SmartImportPage, SmartImportSelection, SmartImportSource, SmartImportView } from "@/lib/smart-import-types";
import { ManagerDialog, ManagerIcon } from "./manager-primitives";
import { SmartFeedback } from "./smart-import-feedback";
import { SMART_BATCH_STATUS } from "./smart-import-list";
import { SmartImportDetail, SmartImportFieldsEditor, SmartImportSourceEditor } from "./smart-import-detail";
import { SmartImportCommit } from "./smart-import-commit";
import { SmartImportUndo } from "./smart-import-undo";
import { SmartAnalysisJobs, SmartImportAnalysis } from "./smart-import-analysis";
import { downloadSmartReport, SmartRequestError, smartDate, smartError, smartErrorStatus, smartRequest } from "./smart-api";
import styles from "./smart-import.module.css";

const VIEWS: { id: SmartImportView; label: string }[] = [{ id: "review", label: "需我处理" }, { id: "suggested", label: "建议可保留" }, { id: "duplicates", label: "重复 / 已有" }, { id: "invalid", label: "无效链接" }, { id: "excluded", label: "已排除来源" }, { id: "all", label: "全部候选" }];
const DECISIONS: Record<SmartImportDecision, string> = { defer: "待决定", keep: "已决定保留", ignore: "已忽略" };
const MATCH = { new: "新候选", existing: "现有收藏", archived: "已归档资源", "published-only": "仅在公开版本" };

export function SmartImportWorkspace({ batchId }: { batchId: string }) {
  const router = useRouter(); const [data, setData] = useState<SmartImportPage | null>(null); const [filters, setFilters] = useState<SmartImportFilters>({ view: "review" }); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [version, setVersion] = useState(0); const [jobsVersion, setJobsVersion] = useState(0);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [status, setStatus] = useState(0); const [message, setMessage] = useState("");
  const [selected, setSelected] = useState<Set<string>>(new Set()); const selectionContext = useRef<SmartImportBatchContext | null>(null);
  const [dialog, setDialog] = useState<"classify" | "commit" | "undo" | "analysis" | "cancel" | "delete" | "filters" | "actions" | null>(null); const [detail, setDetail] = useState<string | null>(null); const [source, setSource] = useState<SmartImportSource | null>(null);
  const [actionContext, setActionContext] = useState<SmartImportBatchContext | null>(null); const [actionScope, setActionScope] = useState<string[]>([]);
  useEffect(() => {
    const controller = new AbortController(); smartRequest<SmartImportPage>("imports", { action: "get", batchId, page, filters }, controller.signal).then(result => setData(result)).catch(failure => { if (!controller.signal.aborted) { setError(smartError(failure)); setStatus(smartErrorStatus(failure)); } }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort();
  }, [batchId, filters, page, version]);
  function reload() { setError(""); setStatus(0); setLoading(true); setVersion(value => value + 1); }
  function changeFilter(next: Partial<SmartImportFilters>) { setFilters(previous => ({ ...previous, ...next })); setPage(1); setLoading(true); }
  function clearFilters() { setFilters({ view: "all" }); setSearch(""); setPage(1); setLoading(true); }
  function changed(result: SmartImportBatchContext) { setData(previous => previous ? { ...previous, ...result } : previous); reload(); }
  function regrouped(result: SmartImportBatchContext) { changed(result); clearSelection(); setMessage("来源与分组已更新，原固定选择已清除。请按最新候选重新选择。"); }
  function clearSelection() { setSelected(new Set()); selectionContext.current = null; }
  function toggle(id: string) { if (!data) return; if (!selected.size) selectionContext.current = data; setSelected(previous => { const next = new Set(previous); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  const allPageSelected = Boolean(data?.groups.some(group => !group.readOnly) && data.groups.filter(group => !group.readOnly).every(group => selected.has(group.id)));
  function selectPage() { if (!data) return; if (!selected.size) selectionContext.current = data; setSelected(previous => { const next = new Set(previous); data.groups.filter(group => !group.readOnly).forEach(group => { if (allPageSelected) next.delete(group.id); else next.add(group.id); }); return next; }); }
  function openDialog(next: NonNullable<typeof dialog>) { if (!data) return; setActionContext(["classify", "commit", "analysis", "actions"].includes(next) ? selectionContext.current ?? data : data); setActionScope([...selected]); setDialog(next); }
  async function selectFiltered() { if (!data || busy) return; setBusy("select"); setError(""); try { const result = await smartRequest<SmartImportSelection>("imports", { action: "select", batchId, batchRevision: data.batchRevision, filters }); selectionContext.current = result; setSelected(new Set(result.groupIds)); setMessage(`已固定选择当前筛选结果的 ${result.total} 个去重组。之后更改筛选不会扩大这次选择。`); } catch (failure) { setError(smartError(failure)); setStatus(smartErrorStatus(failure)); } finally { setBusy(""); } }
  async function decide(decision?: SmartImportDecision, adoptSuggestion = false) { const snapshot = selectionContext.current; if (!snapshot || !selected.size || busy) return; const ids = [...selected]; setBusy("decide"); setError(""); try { const result = await smartRequest<SmartImportBatchContext>("imports", { action: "decide", batchId, batchRevision: snapshot.batchRevision, groupIds: ids, ...(decision ? { decision } : {}), ...(adoptSuggestion ? { adoptSuggestion: true } : {}) }); changed(result); selectionContext.current = result; if (dialog === "actions") setDialog(null); setMessage(adoptSuggestion ? "已采用所选候选的建议。仍需确认私有入库。" : `已保存 ${ids.length} 个候选的“${DECISIONS[decision!]}”决定。`); } catch (failure) { setError(smartError(failure)); setStatus(smartErrorStatus(failure)); } finally { setBusy(""); } }
  async function batchAction(action: "refresh" | "pause" | "resume" | "cancel" | "delete") { const snapshot = dialog ? actionContext : data; if (!snapshot || busy) return; setBusy(action); setError(""); try { const result = await smartRequest<SmartImportBatchContext | { deleted: true }>("imports", { action, batchId, batchRevision: snapshot.batchRevision }); if ("deleted" in result) { router.push("/tools/manage/imports"); return; } changed(result); clearSelection(); setDialog(null); setMessage(action === "pause" ? "本批已暂停，所有人工决定与成功入库结果都已保留。" : action === "resume" ? "已恢复整理，可以从尚未完成的候选继续。" : action === "cancel" ? "本批已取消。人工决定和已入库资源仍保留，可在记录中继续查看。" : "已重新核对现有资源关系，请检查变化后再确认入库。"); } catch (failure) { setError(smartError(failure)); setStatus(smartErrorStatus(failure)); } finally { setBusy(""); } }
  async function report() {
    if (!data || busy) return; setBusy("report"); setError("");
    try { const groups: SmartImportPage["groups"] = []; const invalid: SmartImportSource[] = []; let revision = ""; let summary = data.batch;
      for (const view of ["all", "invalid", "excluded"] as const) { let current = 1; let total = 1; do { const result = await smartRequest<SmartImportPage>("imports", { action: "get", batchId, page: current, filters: { view } }); if (revision && result.batchRevision !== revision) throw new SmartRequestError("批次在导出期间发生变化，请重新下载报告。", 409); revision = result.batchRevision; summary = result.batch; groups.push(...result.groups); invalid.push(...result.invalidSources); total = Math.ceil(result.total / 50); current += 1; } while (current <= total); }
      downloadSmartReport({ exportedAt: new Date().toISOString(), batch: summary, groups, invalidSources: invalid }, `import-report-${batchId}.json`); setMessage("已下载本批处理报告，包含候选、来源摘要和处理结果。");
    } catch (failure) { setError(smartError(failure)); setStatus(smartErrorStatus(failure)); } finally { setBusy(""); }
  }
  function submitSearch(event: FormEvent) { event.preventDefault(); changeFilter({ search: search.trim() || undefined }); }
  const summary = data?.batch.summary; const disabled = loading || Boolean(busy); const frozenContext = actionContext;
  const filterControls = <div className={styles.filters}><select aria-label="来源文件夹" value={filters.folder ?? ""} onChange={event => changeFilter({ folder: event.target.value || undefined })}><option value="">全部文件夹</option>{data?.facets.folders.map(item => <option key={item.value} value={item.value}>{item.value || "未分文件夹"}（{item.count}）</option>)}</select><select aria-label="主域名" value={filters.domain ?? ""} onChange={event => changeFilter({ domain: event.target.value || undefined })}><option value="">全部主域名</option>{data?.facets.domains.map(item => <option key={item.value} value={item.value}>{item.value}（{item.count}）</option>)}</select><select aria-label="资源类型" value={filters.kind ?? ""} onChange={event => changeFilter({ kind: (event.target.value || undefined) as SmartImportFilters["kind"] })}><option value="">全部类型</option>{RESOURCE_KINDS.map(kind => <option key={kind} value={kind}>{RESOURCE_KIND_LABELS[kind]}</option>)}</select><select aria-label="用途分类" value={filters.category ?? ""} onChange={event => changeFilter({ category: (event.target.value || undefined) as SmartImportFilters["category"] })}><option value="">全部用途</option>{RESOURCE_CATEGORIES.map(category => <option key={category}>{category}</option>)}</select><select aria-label="人工决定" value={filters.decision ?? ""} onChange={event => changeFilter({ decision: (event.target.value || undefined) as SmartImportFilters["decision"] })}><option value="">全部决定</option>{Object.entries(DECISIONS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button type="button" className={styles.textLink} onClick={clearFilters}>清除筛选</button></div>;
  return <>
    <div className={styles.breadcrumb}><Link href="/tools/manage/imports">导入记录</Link><span aria-hidden="true">/</span><span>整理这一批</span></div>
    <header className={styles.pageHeader}><div><p className={styles.eyebrow}>MAKE ROOM FOR WHAT MATTERS</p><h1>{data?.batch.name || "导入工作区"}</h1><p>先核对，再保留。所有决定自动保存在这一批。</p></div>{data ? <span className={styles.statusBadge}>{SMART_BATCH_STATUS[data.batch.status]}</span> : null}</header>
    {summary ? <><div className={styles.summaryGrid}><div><strong>{summary.rawTotal.toLocaleString()}</strong><span>原始书签</span></div><div><strong>{summary.groupTotal.toLocaleString()}</strong><span>去重后候选</span></div><div><strong>{summary.pendingGroups.toLocaleString()}</strong><span>尚待处理</span></div><div><strong>{summary.createdResources.toLocaleString()}</strong><span>本批私有新增</span></div></div><p className={styles.summaryCaption}>来源：{summary.validSources} 条有效 · {summary.invalidSources} 条无效 · {summary.excludedSources} 条已排除，其中 {summary.duplicateSources} 条为本批重复来源。候选：{summary.newGroups} 个新候选 · {summary.existingGroups} 个现有收藏 · {summary.archivedGroups} 个已归档 · {summary.publishedOnlyGroups} 个仅在公开版本。</p></> : null}
    {data ? <div className={styles.batchTools}><div className={styles.inlineActions}><button type="button" className={styles.secondaryButton} disabled={disabled} onClick={() => void batchAction(data.batch.status === "paused" || data.batch.status === "cancelled" ? "resume" : "pause")}>{data.batch.status === "paused" || data.batch.status === "cancelled" ? "继续整理" : "暂停整理"}</button><button type="button" className={styles.textLink} disabled={disabled} onClick={() => void batchAction("refresh")}>重新核对重复</button><button type="button" className={styles.textLink} disabled={disabled} onClick={report}>{busy === "report" ? "正在汇总…" : "下载处理报告"}</button></div><details className={styles.batchMore}><summary>批次管理</summary><div><button type="button" disabled={disabled} onClick={() => openDialog("undo")}>撤回本批私有新增</button><button type="button" disabled={disabled} onClick={() => openDialog("cancel")}>取消本批整理</button><button type="button" disabled={disabled} onClick={() => openDialog("delete")}>删除导入记录</button></div></details></div> : null}
    {data?.batch.status === "paused" || data?.batch.status === "cancelled" ? <p className={styles.notice}>这一批已{data.batch.status === "paused" ? "暂停" : "取消"}，已保存的决定和资源不会丢失。点击“继续整理”可接着完成。</p> : null}
    {!dialog ? <SmartFeedback error={error} status={status} message={message} onRefresh={reload} /> : null}
    <SmartAnalysisJobs batchId={batchId} refreshVersion={jobsVersion} onResults={reload} />
    <nav className={styles.viewTabs} aria-label="候选视图">{VIEWS.filter(view => view.id !== "excluded" || summary?.excludedSources).map(view => <button key={view.id} type="button" aria-pressed={filters.view === view.id} onClick={() => changeFilter({ view: view.id })}>{view.label}{view.id === "invalid" && summary?.invalidSources ? <span>{summary.invalidSources}</span> : null}</button>)}</nav>
    <form className={styles.filterSearch} onSubmit={submitSearch}><div><ManagerIcon name="search" /><input type="search" aria-label="搜索本批标题或链接" placeholder="搜索标题或链接…" value={search} onChange={event => setSearch(event.target.value)} /></div><button type="submit" className={styles.secondaryButton}>搜索</button></form>
    {!(filters.view === "invalid" || filters.view === "excluded") ? <><div className={styles.desktopFilters}>{filterControls}</div><button type="button" className={`${styles.secondaryButton} ${styles.mobileFilterButton}`} onClick={() => openDialog("filters")}><ManagerIcon name="list" />筛选候选</button></> : null}
    {selected.size ? <section className={styles.selectionBar} aria-label="已选候选操作"><div><strong>已固定选择 {selected.size} 个去重组</strong><span>含其他页和其他筛选下的选择；操作仅作用于这些编号。</span></div><div className={styles.inlineActions}><button type="button" disabled={disabled} onClick={() => void decide("keep")}>保留</button><button type="button" disabled={disabled} onClick={() => void decide("defer")}>稍后决定</button><button type="button" disabled={disabled} onClick={() => void decide("ignore")}>忽略</button><button type="button" disabled={disabled} onClick={() => openDialog("classify")}>调整分类</button><button type="button" disabled={disabled} onClick={() => void decide(undefined, true)}>采用分类建议</button><button type="button" disabled={disabled} onClick={() => openDialog("analysis")}>智能分析所选</button><button type="button" className={styles.primaryButton} disabled={disabled || ["paused", "cancelled"].includes(data?.batch.status ?? "")} onClick={() => openDialog("commit")}>预览私有入库</button><button type="button" onClick={clearSelection} disabled={Boolean(busy)}>取消选择</button></div></section> : null}
    {loading ? <p className={styles.loading} role="status">正在读取这一页候选…</p> : data && data.total ? <>
      {!(filters.view === "invalid" || filters.view === "excluded") ? <div className={styles.listToolbar}><label className={styles.checkLabel}><input type="checkbox" checked={allPageSelected} onChange={selectPage} disabled={Boolean(busy)} />选择本页 {data.groups.filter(group => !group.readOnly).length} 组</label><button type="button" className={styles.textLink} disabled={Boolean(busy)} onClick={selectFiltered}>选择当前筛选的全部可处理组</button></div> : <p className={styles.help}>{filters.view === "excluded" ? "已排除的来源仍保留。打开后取消排除，即可重新参与去重。" : "无效链接先留在这里。修正后重新参与去重，或排除此来源。"}</p>}
      {(filters.view === "invalid" || filters.view === "excluded") ? <ul className={styles.candidateList}>{data.invalidSources.map(item => <li key={item.id} className={styles.invalidRow}><div><strong>{item.name || "未命名书签"}</strong><p className={styles.fullUrl}>{item.url}</p><p className={styles.noticeText}>{item.invalidReason}</p><p className={styles.help}>{item.sourceFolder || "未分文件夹"}</p></div><button type="button" className={styles.secondaryButton} onClick={() => setSource(item)}>修正或排除</button></li>)}</ul> : <ul className={styles.candidateList} aria-label="本页去重候选">{data.groups.map(group => <li key={group.id} className={`${styles.candidateRow} ${selected.has(group.id) ? styles.selectedRow : ""}`}><label className={styles.rowCheckbox}><input type="checkbox" aria-label={`选择 ${group.fields.name}`} checked={selected.has(group.id)} disabled={Boolean(busy) || group.readOnly} onChange={() => toggle(group.id)} /></label><div className={styles.candidateMain}><button type="button" className={styles.candidateName} onClick={() => setDetail(group.id)}>{group.fields.name || "未命名候选"}</button><p className={styles.candidateUrl}>{group.representative.url}</p><p className={styles.candidateDescription}>{group.fields.description || group.suggestion?.description || "还没有用途说明，打开详情补充。"}</p><div className={styles.candidateMeta}>{!group.categoryConfirmed && group.suggestion ? <><span className={styles.suggestedClassification}>{group.suggestion.source === "model" ? "模型" : "规则"}建议：{RESOURCE_KIND_LABELS[group.suggestion.kind]} · {group.suggestion.category}（{group.suggestion.confidence === "clear" ? "较明确，待采纳" : "需复核，待采纳"}）</span><span>当前候选：{RESOURCE_KIND_LABELS[group.fields.kind]} · {group.fields.category}（待确认）</span></> : <span>{group.categoryConfirmed ? "已确认：" : "当前候选："}{RESOURCE_KIND_LABELS[group.fields.kind]} · {group.fields.category}{!group.categoryConfirmed ? "（待确认）" : ""}</span>}<span>{group.sourceCount} 条来源 · {MATCH[group.matchKind]}</span></div>{group.reviewRequired ? <p className={styles.noticeText}>需要复核：{group.reviewReasons.join("；")}</p> : null}{group.error ? <p className={styles.noticeText}>{group.error}</p> : null}</div><div className={styles.candidateEnd}><span className={styles.statusBadge}>{group.readOnly ? "已处理" : DECISIONS[group.decision]}</span><button type="button" className={styles.textLink} onClick={() => setDetail(group.id)}>查看详情 <span aria-hidden="true">→</span></button></div></li>)}</ul>}
      <div className={styles.pagination}><span>第 {data.page} / {Math.max(1, Math.ceil(data.total / 50))} 页 · 共 {data.total} {(filters.view === "invalid" || filters.view === "excluded") ? "条来源" : "个去重组"}</span><div className={styles.inlineActions}><button type="button" className={styles.secondaryButton} disabled={page <= 1 || Boolean(busy)} onClick={() => { setLoading(true); setPage(value => value - 1); }}>上一页</button><button type="button" className={styles.secondaryButton} disabled={page * 50 >= data.total || Boolean(busy)} onClick={() => { setLoading(true); setPage(value => value + 1); }}>下一页</button></div></div>
    </> : !loading ? <div className={styles.empty}><ManagerIcon name="check" /><h2>{filters.view === "review" ? "这一页暂时没有待处理候选" : "没有匹配的候选"}</h2><p>{filters.view === "review" ? "可以查看建议、重复项或全部候选，已保存的决定都在原处。" : "调整筛选条件，或查看这一批全部候选。"}</p><button type="button" className={styles.secondaryButton} onClick={clearFilters}>查看全部候选</button></div> : null}
    {data ? <footer className={styles.workbenchFooter}><p>更新于 {smartDate(data.batch.updatedAt)} · 私有入库与发布到网站是独立步骤。</p><Link className={styles.textLink} href={`/tools/manage?batchId=${encodeURIComponent(batchId)}`}>查看本批收藏 →</Link></footer> : null}
    {selected.size ? <div className={styles.selectionDock} aria-label="所选候选快捷操作"><strong>已选 {selected.size} 组<small>范围已固定</small></strong><div><button type="button" className={styles.secondaryButton} disabled={disabled} onClick={() => openDialog("actions")}>批量操作</button><button type="button" className={styles.primaryButton} disabled={disabled || ["paused", "cancelled"].includes(data?.batch.status ?? "")} onClick={() => openDialog("commit")}>预览入库</button></div></div> : null}
    {dialog === "filters" ? <ManagerDialog title="筛选本批候选" description="切换筛选只改变展示范围，已选编号会保持。" onClose={() => setDialog(null)}><div className={styles.dialogBody}>{filterControls}<div className={styles.dialogActions}><button type="button" className={styles.primaryButton} onClick={() => setDialog(null)}>查看筛选结果</button></div></div></ManagerDialog> : null}
    {dialog === "actions" ? <ManagerDialog title={`处理已选的 ${selected.size} 个候选`} description="含其他页和其他筛选下的选择，操作只作用于已固定的编号。" onClose={() => setDialog(null)} busy={Boolean(busy)}><div className={styles.dialogBody}><SmartFeedback error={error} status={status} /><div className={styles.mobileBulkActions}><button type="button" className={styles.secondaryButton} disabled={disabled} onClick={() => void decide("keep")}>保留</button><button type="button" className={styles.secondaryButton} disabled={disabled} onClick={() => void decide("defer")}>稍后决定</button><button type="button" className={styles.secondaryButton} disabled={disabled} onClick={() => void decide("ignore")}>忽略</button><button type="button" className={styles.secondaryButton} disabled={disabled} onClick={() => openDialog("classify")}>调整分类</button><button type="button" className={styles.secondaryButton} disabled={disabled} onClick={() => void decide(undefined, true)}>采用分类建议</button><button type="button" className={styles.secondaryButton} disabled={disabled} onClick={() => openDialog("analysis")}>智能分析所选</button></div><div className={styles.dialogActions}><button type="button" className={styles.textLink} disabled={Boolean(busy)} onClick={() => { clearSelection(); setDialog(null); }}>取消全部选择</button><button type="button" className={styles.primaryButton} disabled={disabled || ["paused", "cancelled"].includes(data?.batch.status ?? "")} onClick={() => openDialog("commit")}>预览私有入库</button></div></div></ManagerDialog> : null}
    {detail && data ? <SmartImportDetail context={data} groupId={detail} onClose={() => setDetail(null)} onChanged={changed} onRegrouped={regrouped} /> : null}{source && data ? <SmartImportSourceEditor context={data} source={source} onClose={() => setSource(null)} onChanged={regrouped} /> : null}
    {dialog === "classify" && frozenContext ? <SmartImportFieldsEditor context={frozenContext} groupIds={actionScope} onClose={() => setDialog(null)} onChanged={result => { changed(result); selectionContext.current = result; }} /> : null}
    {dialog === "commit" && frozenContext ? <SmartImportCommit context={frozenContext} groupIds={actionScope} onClose={() => { setDialog(null); clearSelection(); reload(); }} onChanged={changed} /> : null}
    {dialog === "undo" && frozenContext ? <SmartImportUndo context={frozenContext} onClose={() => { setDialog(null); clearSelection(); }} onChanged={changed} /> : null}
    {dialog === "analysis" && frozenContext ? <SmartImportAnalysis context={frozenContext} groupIds={actionScope} onClose={() => setDialog(null)} onStarted={() => { setJobsVersion(value => value + 1); setMessage("智能分析已开始，进度会保存在本批。返回的建议仍需你确认采用。"); }} /> : null}
    {(dialog === "cancel" || dialog === "delete") && frozenContext ? <ManagerDialog title={dialog === "delete" ? "删除这条导入记录？" : "取消本批整理？"} description={dialog === "delete" ? "删除导入来源与候选记录后无法继续此批。已成功入库的资源会保留，不会从收藏或公开页移除。" : "停止这批的后续入库。来源、人工决定与成功入库的部分都会保留。"} onClose={() => setDialog(null)} busy={Boolean(busy)}><div className={styles.dialogBody}><SmartFeedback error={error} status={status} /><div className={styles.dialogActions}><button type="button" className={styles.secondaryButton} disabled={Boolean(busy)} onClick={() => setDialog(null)}>返回</button><button type="button" className={styles.dangerButton} disabled={Boolean(busy)} onClick={() => void batchAction(dialog)}>{busy ? "正在处理…" : dialog === "delete" ? "确认删除导入记录" : "确认取消本批"}</button></div></div></ManagerDialog> : null}
  </>;
}
